networks:
  traefik:
    external: true
    name: traefik

services:
  tvtracker:
    container_name: tvtracker
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./prisma/database:/app/prisma/database
    ports:
      - 3008:3000
    networks:
      - traefik
    env_file:
      - ./.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.tvtracker.entrypoints=https
      - traefik.http.routers.tvtracker.rule=Host(`tv.home.marionetmarin.fr`)
      - traefik.http.routers.tvtracker.tls=true  
      - traefik.http.routers.tvtracker.tls.certresolver=letsencrypt
      - traefik.http.services.tvtracker.loadbalancer.server.port=3000
